config/routes.rb
# frozen_string_literal: true

Spina::Engine.routes.draw do
  namespace :frontend, path: 'conferences', module: 'conferences/primer_theme/conferences' do
    resources :conferences, only: %i[index show] do
      resources :presentations, only: [:show]
    end
    resources :presentations, only: [:show]
    get 'cookies-info', controller: 'application'
  end

  namespace :frontend, path: 'journal', module: 'conferences/primer_theme/journal' do
    resources :issues, only: %i[index show] do
      resources :articles, only: %i[show]
    end
  end
end

app/controllers/spina/conferences/primer_theme/journal/application_controller.rb
# frozen_string_literal: true

module Spina
  module Conferences
    module PrimerTheme
      module Journal
        # Base class from which controllers related to the journal plugin inherit
        class ApplicationController < Spina::ApplicationController
        end
      end
    end
  end
end

app/controllers/spina/conferences/primer_theme/journal/articles_controller.rb
# frozen_string_literal: true

module Spina
  module Conferences
    module PrimerTheme
      module Journal
        # User-facing controller for journal articles
        class ArticlesController < ApplicationController
          before_action :set_article, :set_issue, :set_journal, :set_licence, :set_breadcrumb, :set_metadata, :require_admin_for_invisible_article

          def show
            respond_to do |format|
              format.html { add_breadcrumb @article.title }
              format.pdf do
                if @article.has_content?(:attachment)
                  redirect_to main_app.url_for(@article.content(:attachment))
                else
                  send_file Rails.root.join('public/404.html'), type: 'text/html; charset=utf-8', status: 404
                end
              end
            end
          end

          private

          def set_article
            @article = Admin::Journal::Article.includes(affiliations: [:institution]).find(params[:id])
          rescue ActiveRecord::RecordNotFound
            send_file Rails.root.join('public/404.html'), type: 'text/html; charset=utf-8', status: 404
          end

          def set_issue
            @issue = Admin::Journal::Issue.includes(:volume, :articles).find(params[:issue_id])
          rescue ActiveRecord::RecordNotFound
            send_file Rails.root.join('public/404.html'), type: 'text/html; charset=utf-8', status: 404
          end

          def set_journal
            @journal = @issue.volume.journal
          end

          def set_licence
            @licence = @article.licence
          end

          def set_breadcrumb
            return if @issue.blank?

            add_breadcrumb @journal.name, frontend_issues_path
            add_breadcrumb Admin::Journal::Issue.model_name.human.pluralize, frontend_issues_path
            add_breadcrumb t('spina.conferences.primer_theme.journal.volume_issue', volume_number: @issue.volume.number, issue_number: @issue.number),
                          frontend_issue_path(@issue.id)
          end

          def set_metadata
            @title = @article.title
            @description = @article.content(:abstract).try(:to_plain_text)
          end

          def require_admin_for_invisible_article
            raise ActiveRecord::RecordNotFound unless current_spina_user.present? || @article.visible?
          rescue ActiveRecord::RecordNotFound # TODO: proper 404 handler
            send_file Rails.root.join('public/404.html'), type: 'text/html; charset=utf-8', status: 404
          end
        end
      end
    end
  end
end

app/controllers/spina/conferences/primer_theme/journal/issues_controller.rb
# frozen_string_literal: true

module Spina
  module Conferences
    module PrimerTheme
      module Journal
        # User-facing controller for journal issues
        class IssuesController < ApplicationController
          before_action :set_journal
          before_action :set_issue, :set_breadcrumb, only: :show
          before_action :set_metadata

          def index
            # having multiple journals is not currently allowed anyway
            @issues = if current_spina_user.present?
                        Admin::Journal::Issue.sorted_desc
                      else
                        Admin::Journal::Issue.sorted_desc.where('date <= ?', Time.zone.today)
                      end
            @latest_issue = @issues.first
          end

          def show
            @articles = current_spina_user.present? ? @issue.articles : @issue.articles.visible
            add_breadcrumb t('spina.conferences.primer_theme.journal.volume_issue', volume_number: @issue.volume.number, issue_number: @issue.number)
          end

          private

          def set_journal
            @journal = Admin::Journal::Journal.instance
          end

          def set_issue
            @issue = Admin::Journal::Issue.includes(:volume, :articles).find(params[:id])
          rescue ActiveRecord::RecordNotFound
            send_file Rails.root.join('public/404.html'), type: 'text/html; charset=utf-8', status: 404
          end

          def set_breadcrumb
            add_breadcrumb @journal.name, frontend_issues_path
            add_breadcrumb Admin::Journal::Issue.model_name.human.pluralize, frontend_issues_path
          end

          def set_metadata
            @title = @journal.name
            @description = ActionView::Base.full_sanitizer.sanitize(@journal.content(:description))
          end
        end
      end
    end
  end
end

app/views/spina/conferences/primer_theme/journal/articles/_affiliation.html.haml
= render(Primer::FlexComponent.new(tag: :li, mr: 4, align_items: :center)) do
  = render(Primer::FlexItemComponent.new(mr: 2)) do
    = render(Primer::OcticonComponent.new('person'))
  = render(Primer::FlexComponent.new(tag: :address, direction: :column)) do
    = render(Primer::TextComponent.new(tag: :div, font_weight: :bold)) { affiliation.name }
    = render(Primer::TextComponent.new(tag: :div, color: :text_secondary)) { affiliation.institution.name }

app/views/spina/conferences/primer_theme/journal/articles/_authorship.html.haml
= render(Primer::FlexComponent.new(tag: :li, mr: 4, align_items: :center)) do
  = render(Primer::FlexItemComponent.new(mr: 2)) do
    = render(Primer::OcticonComponent.new('person'))
  = render(Primer::FlexComponent.new(tag: :address, direction: :column)) do
    = render(Primer::TextComponent.new(tag: :div, font_weight: :bold)) { authorship.affiliation.name }
    = render(Primer::TextComponent.new(tag: :div, color: :text_secondary)) { authorship.affiliation.institution.name }

app/views/spina/conferences/primer_theme/journal/articles/_metadata.html.haml
- content_for :head do
  %link{ rel: 'schema.DC', href: 'http://purl.org/dc/elements/1.1/' }
  - @article.authorships.sorted_within_article.each do |authorship|
    %meta{ name: 'DC.Creator.PersonalName', content: authorship.affiliation.name }
  %meta{ name: 'DC.Date.created', scheme: 'ISO8601', content: @issue.date.to_s(:iso8601) }
  %meta{ name: 'DC.Date.issued', scheme: 'ISO8601', content: @issue.date.to_s(:iso8601) }
  %meta{ name: 'DC.Date.modified', scheme: 'ISO8601', content: @issue.date.to_s(:iso8601) }
  - if @article.has_content? :attachment
    %meta{ name: 'DC.Format', scheme: 'IMT', content: 'application/pdf' }
  %meta{ name: 'DC.Identifier', content: @article.id }
  %meta{ name: 'DC.Identifier.URI', content: frontend_issue_article_url(@issue.id, @article.id) }
  - if @article.has_content? :page_range
    %meta{ name: 'DC.Identifier.pageNumber', content: "#{@article.content(:page_range).first_page}-#{@article.content(:page_range).last_page}" }
  %meta{ name: 'DC.Language', scheme: 'ISO639-1', content: 'en' }
  %meta{ name: 'DC.Rights', content: "Copyright © #{@article.issue.date.year} #{@article.affiliations.collect(&:name).to_sentence}"  }
  - if @licence && @licence.has_content?(:url) && !@licence.content(:url).blank?
    %meta{ name: 'DC.Rights', content: @licence.content(:url) }
  %meta{ name: 'DC.Source', content: @journal.name }
  %meta{ name: 'DC.Title', content: @article.title }
  %meta{ name: 'DC.Type', content: 'Text.Serial.Journal' }
  %meta{ name: 'DC.Type', 'xml:lang': 'en', content: 'text' }

  %meta{ name: 'gs_meta_revision', content: '1.1' }

  %meta{ name: 'citation_journal_title', content: @journal.name }
  - if @journal.has_content?(:journal_abbreviation)
    %meta{ name: 'citation_journal_abbrev', content: @journal.content(:journal_abbreviation) }
  - if @journal.has_content?(:issn)
    %meta{ name: 'citation_issn', content: @journal.content(:issn) }
  - @article.authorships.sorted_within_article.each do |authorship|
    %meta{ name: 'citation_author', content: authorship.affiliation.name }
    %meta{ name: 'citation_author_institution', content: authorship.affiliation.institution.name }
  %meta{ name: 'citation_language', content: 'en' }
  %meta{ name: 'citation_date', content: @issue.date.to_s(:iso8601).gsub('-', '/') }
  %meta{ name: 'citation_volume', content: @issue.volume.number }
  %meta{ name: 'citation_issue', content: @issue.number }
  - if @article.has_content? :page_range
    %meta{ name: 'citation_firstpage', content: @article.content(:page_range).first_page }
    %meta{ name: 'citation_lastpage', content: @article.content(:page_range).last_page }
  %meta{ name: 'citation_abstract_html_url', content: frontend_issue_article_url(@issue.id, @article.id) }
  %meta{ name: 'citation_pdf_url', content: frontend_issue_article_url(@issue.id, @article.id) + '.pdf' }

app/views/spina/conferences/primer_theme/journal/articles/show.html.haml
- cache [@article, @article.authorships, @article.affiliations, @article.content(:abstract), @article.issue, @article.issue.volume, @article.issue.content(:cover_img)] do
  = render partial: 'metadata'

  = render(Primer::HeadingComponent.new) { @article.title }

  = render(Primer::FlexComponent.new(direction: [:column, nil, :row, nil])) do
    = render(Primer::FlexItemComponent.new(flex_auto: true, mr: [nil, nil, 4, nil])) do
      %ul.list-style-none.d-flex.flex-column.flex-sm-row.my-2
        - @article.affiliations.each do |affiliation|
          = render(Primer::FlexComponent.new(tag: :li, mr: 4, align_items: :center)) do
            = render(Primer::FlexItemComponent.new(mr: 2)) do
              = render(Primer::OcticonComponent.new('person'))
            = render(Primer::FlexComponent.new(tag: :address, direction: :column)) do
              = render(Primer::TextComponent.new(tag: :div, font_weight: :bold)) { affiliation.name }
              = render(Primer::TextComponent.new(tag: :div, color: :text_secondary)) { affiliation.institution.name }

      - if @article.has_content?(:abstract)
        = render(Primer::HeadingComponent.new(tag: :h2, mt: 4, font_size: 3)) { t '.abstract' }
        = render(Primer::MarkdownComponent.new) { @article.content.html(:abstract) }

    = render(Primer::BorderBoxComponent.new(ml: [nil, nil, 4, nil], style: 'min-width: 20vw')) do |sidebar|
      - sidebar.body do
        - if @article.issue.has_content?(:cover_img)
          = render partial: 'spina/conferences/primer_theme/journal/issues/issue_cover', locals: { issue: @article.issue, cover_img: @article.issue.content(:cover_img), size: [200, 400] }
        = render(Primer::BorderBoxComponent.new) do |component|
          - if @article.has_content?(:attachment)
            - component.row do
              = render(Primer::ButtonComponent.new(tag: :a, href: frontend_issue_article_path(@issue, @article, format: :pdf), download: '', scheme: :primary)) do
                = render Primer::OcticonComponent.new('download')
                = t '.download'
          - component.row do
            = render(Primer::HeadingComponent.new(tag: :h2, font_size: 4, color: :text_secondary)) { t '.published' }
            = render(Primer::TextComponent.new) do
              = time_tag @article.issue.date, format: :long
          - component.row do
            = render(Primer::HeadingComponent.new(tag: :h2, font_size: 4, color: :text_secondary)) { t '.issue' }
            = render(Primer::TextComponent.new) do
              = link_to t('spina.conferences.primer_theme.journal.volume_issue',
                          volume_number: @article.issue.volume.number,
                          issue_number: @article.issue.number), frontend_issue_path(@article.issue)
          - unless @article.doi.blank?
            - component.row do
              = render(Primer::HeadingComponent.new(tag: :h2, font_size: 4, color: :text_secondary)) { t '.doi' }
              = render(Primer::TextComponent.new(tag: :div, color: :text_secondary, mt: 1)) do
                = link_to nil, @article.doi
          - unless @article.url.blank?
            - component.row do
              = render(Primer::HeadingComponent.new(tag: :h2, font_size: 4, color: :text_secondary)) { t '.url' }
              = render(Primer::TextComponent.new(tag: :div, color: :text_secondary, mt: 1)) do
                = link_to nil, @article.url
          - component.row do
            = render(Primer::FlexComponent.new(direction: :column)) do
              = render(Primer::TextComponent.new(mb: 2)) do
                Copyright © #{@article.issue.date.year} #{@article.affiliations.collect(&:name).to_sentence}
              - unless @licence.nil?
                - cache [@licence, @licence.content(:logo), @licence.content(:url)] do
                  %a{ rel: 'licence', href: @licence.content(:url) }
                    - if @licence.has_content?(:logo)
                      = image_tag main_app.url_for(@licence.content(:logo).variant(resize_to_limit: [200, 200])),
                                  srcset: srcset(@licence.content(:logo), variant: { resize_to_limit: [200, 200] }),
                                  alt_description: t('.licence_logo'),
                                  draggable: false,
                                  class: 'py-1'
            - unless @licence.nil?
              - cache [@licence, @licence.content(:text)] do
                = @licence.has_content?(:text) && render(Primer::TextComponent.new(mt: 1)) { @licence.content(:text) }

          - if @article.draft?
            - component.row do
              = render(Primer::TextComponent.new(tag: :div, color: :text_danger, font_weight: :bold)) { t '.draft' }